<?php

/**
*  Block helper for rendering a given webform submission
*/
function s4_webform_render_submission($field) {
  $node = menu_get_object();
  $sid = field_get_items('node', $node, $field);
  $site = field_get_items('node', $node, 'field_site');
  $site = node_load($site[0]['nid']);
  $form = field_get_items('node', $site, 'field_site_form');
  $form = node_load($form[0]['nid']);
  $output = '';
  if (count($form)) {
    module_load_include('inc', 'webform', 'includes/webform.submissions');
    $submission = webform_get_submission($form->nid, $sid[0]['value']);
      if (!$submission) {
        return NULL;
      }
      foreach ($form->webform['components'] as $k => $component) {
        $output .= '<p><span class="form-label">' . $component['name'] . ':</span>';
        $output .= '<span class="form-value">' . implode("\n", $submission->data[$k]['value']) . '</span></p>';
      }
      
          return array('subject' => 'Signup form',
                'content' => $output);
  }
}

/**
*	Implementation of hook_menu_alter
*/
function s4_webform_menu_alter(&$items) {
	$items['node/%webform_menu/webform']['title'] = 'Edit form';
	$items['node/%webform_menu/webform/components']['title'] = 'Edit questions';
	$items['node/%webform_menu/webform/components/%webform_menu_component']['title'] = 'Edit/Add question';
}

function s4_webform_form_webform_components_form_alter(&$form, $form_state) {
	$form['add']['type']['#options']['markup'] = 'Additional directions';
	$form['add']['type']['#options']['fieldset'] = 'Collection of questions';
	$form['add']['type']['#options']['textfield'] = 'Single-line text';
	$form['add']['type']['#options']['textarea'] = 'Paragraph text';
	$form['add']['type']['#options']['select'] = 'Drop-down list';
	unset($form['add']['type']['#options']['hidden']);	
}

function s4_webform_form_webform_component_edit_form_alter(&$form, $form_state) {
	$form['form_key']['#title'] = t('Short machine name');
	$form['form_key']['#description'] = t('Enter a computer-readable version of this question. This can only contain letters, numbers, and underscores (_).');
}