language: php

php:
  - 5.3


mysql:
  database: drupal
  username: root
  encoding: utf8


before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - pear install PHP_CodeSniffer
  - wget http://ftp.drupal.org/files/projects/drupalcs-7.x-1.0-beta1.tar.gz -O drupalcs.tar.gz
  - tar -xvzf drupalcs.tar.gz -C ./
  - echo "error_reporting=E_ERROR" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - echo "memory_limit=200M" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - phpenv rehash
  - drush make https://raw.github.com/calstates4/s4project/dev/distro.make student_signup
  - cd student_signup
  - drush si student_signup --db-url=mysql://root:@127.0.0.1/drupal  --yes || true
  - drush cc all --yes

script: 
  - test -d profiles/student_signup
  - test -d profiles/student_signup/modules/contrib
  - test -d profiles/student_signup/modules/s4_features
  - test -d profiles/student_signup/themes
