language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8
  
before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - echo "error_reporting=E_ERROR" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - phpenv rehash
  - drush make https://raw.github.com/kevee/csu_student_signup/master/distro.make student_signup
  - cd student_signup
  - drush si student_signup --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=s4Test --account-mail=s4@csumb.edu --site-mail=s4@csumb.edu --site-name="S4" --yes
  - drush cc all --yes

script: 
  - test -d profiles/student_signup
  - test -d profiles/student_signup/modules/contrib
  - test -d profiles/student_signup/modules/s4_features
  - test -d profiles/student_signup/themes