<?php


/**
*  Implementaiton of hook_menu
*/
function s4_pages_menu() {
  $items = array();
  $items['homepage'] = array(
    'title' => 'Home page',
    'page callback' => '_s4_pages_homepage',
    'access arguments' => array('access content'),
  );
  
  $items['dashboard'] = array(
    'title' => '',
    'page callback' => '_s4_pages_homepage',
    'access arguments' => array('access s4 dashboard'),
  );
  
  $items['node/%node/students'] = array(
    'title' => 'Students',
    'type' => MENU_LOCAL_TASK,
    'page callback' => '_s4_pages_homepage',
    'access callback' => '_s4_pages_site_student_access',
    'access arguments' => array(1),
    'weight' => 1,
  );
  
  return $items;
}

function s4_pages_menu_alter(&$items) {
	$items['node/%node/revisions']['title'] = 'History';
}

function _s4_pages_site_student_access($node) {
  return (node_access('update', $node) && $node->type == 'site');
}

function _s4_pages_homepage() {
  return '';
}  

function s4_pages_permission() {
  return array(
    'access s4 dashboard' => array(
      'title' => t('Access the dashboard'), 
      'description' => t('Allow the user to access the dashboard.'),
    ),
  );
}

/**
*  Implementation of hook_block_info
*/
function s4_pages_block_info() {
  $blocks['overview_paragraph']['info'] = 'Overview paragraph';
  $blocks['dashboard_title']['info']    = 'Dashboard header';
  $blocks['add_contact_record']['info'] = 'Add contact record button';
  $blocks['add_site_file']['info']    = 'Add site file button';
  return $blocks;
}

/**
*  Implementation of hook_block_view
*/
function s4_pages_block_view($delta) {
  $function_name = 's4_pages_' . $delta;
  if (function_exists($function_name)) {
    return $function_name();
  }
}

/**
*  Add content button for site contact records (appears in the site contact record & files page)
*/

function s4_pages_add_contact_record() {
  $node = menu_get_object();
  return array('subject' => NULL,
         'content' => '<h2>Contact records</h2><div class="spacer-30">' .
                 l('<span class="add"></span>Add new record', 
                 'node/add/contact-record/' . $node->nid,
                 array('html' => TRUE,
                     'attributes' => array('class' => 'button add'),
                     'query' => array('destination' => 
                       'node/' . $node->nid . '/contact-files')))
                  . '</div>');
}

/**
*  Add content button for site files (appears in the site contact record & files page)
*/
function s4_pages_add_site_file() {
  $node = menu_get_object();
  return array('subject' => NULL,
         'content' => '<h2>Site files</h2><div class="spacer-30">' .
                 l('<span class="add"></span>Add new file', 
                 'node/add/file/' . $node->nid,
                 array('html' => TRUE,
                     'attributes' => array('class' => 'button add'),
                     'query' => array('destination' => 
                       'node/' . $node->nid . '/contact-files')))
                  . '</div>');
}

/**
*  Implementation of hook_theme
*/
function s4_pages_theme() {
  return array(
    'overview_paragraph' => array(
      'variables' => array('data' => array()),
      'template'  => 'overview_paragraph',
    ),
  );
}

/**
*  Overview paragraph;
*/
function s4_pages_overview_paragraph() {
  drupal_add_css(drupal_get_path('module', 's4_pages') . '/css/overview.css');
  if ($cache = cache_get('s4_pages_overview_data')) {
    $data = $cache->data;
  }
  else {
    $data = array();
    $query = db_select('location', 'l')
         ->fields('l', array('city', 'province'))
         ->distinct();
    $data['cities'] = $query->countQuery()->execute()->fetchField();

    $query = db_select('node', 'n')
         ->fields('n', array('nid'))
         ->condition('type', 'site')
         ->condition('status', 1)
         ->distinct();
    $data['sites'] = $query->countQuery()->execute()->fetchField();
    
    $query = db_select('node', 'n')
         ->fields('n', array('nid'))
         ->condition('type', 'signup')
         ->condition('status', 1)
         ->distinct();
    $data['students'] = $query->countQuery()->execute()->fetchField();
    cache_set('s4_pages_overview_data', $data, 'cache', CACHE_TEMPORARY);
  }
  if($data['sites'] == 0) {
  	return null;
  }
  return array('subject' => NULL,
         'content' => theme('overview_paragraph', array('data' => $data)));
}

/**
*  Homepage welcome message
*/
function s4_pages_dashboard_title() {
  global $user;
  foreach($user->roles as $role) {
  	if($role == 'staff') {
  		return null;
  	}
  }
  $user = user_load($user->uid);
  $values = field_get_items('user', $user, 'field_first_name');
  $name = ($values[0]['value'])
      ? $values[0]['value']
      : $user->name;
  $title = (isset($_GET['finished']))
       ? t('Great, @name, you\'re all signed up!',
                 array('@name' => $name))
       : t('Hi, @name, what would you like to do?',
                 array('@name' => $name));
  return array('subject' => NULL,
         'content' => '<h1>' . $title . '</h1>');
}