<?php

function s4_api_db_menu() {
	$items = array();
	
	$items['admin/config/s4/db-api'] = array(
		'title' => 'Database Integration',
		'description' => 'Configure direct database integration with your Student Information System.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('s4_api_db_admin_form'),
		'access arguments' => array('administer site configuration'),
	);
	
	return $items;
}

function s4_api_db_admin_form() {
	$form = array();
		
	$form['account'] = array(
		'#type' => 'fieldset',
		'#title' => 'Database account',
		'#collapsible' => TRUE,
	);
	
	$form['account']['s4_api_db_driver'] = array(
		'#markup' => 'These are your available database drivers. If you do not see the driver in this list, you need to install the protocol as a <a href="http://www.php.net/manual/en/pdo.drivers.php">PDO driver in PHP</a>:'.
					 theme('item_list', array('items' => PDO::getAvailableDrivers()))
	);
	
	$form['account']['s4_api_db_dsn'] = array(
		'#type' => 'textfield',
		'#title' => 'Connection URI',
		'#description' => 'The connection DSN to your database. '.
						   l('Read more about DSNs', 'http://www.php.net/manual/en/pdo.construct.php'),
		'#default_value' => variable_get('s4_api_db_dsn', ''),
	);
	
	$form['account']['s4_api_db_username'] = array(
		'#type' => 'textfield',
		'#title' => 'Database username',
		'#default_value' => variable_get('s4_api_db_username', ''),
	);
	
	$form['account']['s4_api_db_password'] = array(
		'#type' => 'password',
		'#title' => 'Database password',
		'#default_value' => variable_get('s4_api_db_password', ''),
	);
	
	$form['queries'] = array(
		'#type' => 'fieldset',
		'#title' => 'Queries',
	);
	
	$form['queries']['s4_api_db_sql_term'] = array(
		'#type' => 'textarea',
		'#title' => 'Query to select terms',
		'#description' => 'Enter the SQL query to use to select terms. The query should use the following tokens: <strong>:start_date</strong> for the start date to search for, and <strong>:end_date</strong> for the end date.',
		'#default_value' => variable_get('s4_api_db_sql_term', ''),
	);
	
	$form['queries']['s4_api_db_sql_courses'] = array(
		'#type' => 'textarea',
		'#title' => 'Query to select courses',
		'#description' => 'Enter the SQL query to use to select courses for a term. The query should use the following tokens: <strong>:term</strong> for the term code.',
		'#default_value' => variable_get('s4_api_db_sql_courses', ''),
	);
	
	$form['queries']['s4_api_db_sql_course_faculty'] = array(
		'#type' => 'textarea',
		'#title' => 'Query to select course faculty',
		'#description' => 'Enter the SQL query to use to select faculty for a course. The query should use the following tokens: <strong>:term</strong> for the term code, <strong>:subject</strong> for the subject, <strong>:catalog_number</strong> for the catalog number, and <strong>:section</strong> for the section.',
		'#default_value' => variable_get('s4_api_db_sql_course_faculty', ''),
	);
	
	$form['queries']['s4_api_db_sql_course_enrollment'] = array(
		'#type' => 'textarea',
		'#title' => 'Query to select course student enrollment',
		'#description' => 'Enter the SQL query to use to select students for a course. The query should use the following tokens: <strong>:term</strong> for the term code, <strong>:subject</strong> for the subject, <strong>:catalog_number</strong> for the catalog number, and <strong>:section</strong> for the section.',
		'#default_value' => variable_get('s4_api_db_sql_course_enrollment', ''),
	);
	
	$form['queries']['s4_api_db_sql_user_enrollment'] = array(
		'#type' => 'textarea',
		'#title' => 'Query to select a user\'s enrollment',
		'#description' => 'Enter the SQL query to use to select a user\'s courses for a term. The query should use the following tokens: <strong>:user_id</strong> for the user\'s unique ID and <strong>:term</strong> for the term code.',
		'#default_value' => variable_get('s4_api_db_sql_user_enrollment', ''),
	);
	
	$form['queries']['s4_api_db_sql_faculty_courses'] = array(
		'#type' => 'textarea',
		'#title' => 'Query to select a faculty\'s courses',
		'#description' => 'Enter the SQL query to use to select a faculty\'s courses for a term. The query should use the following tokens: <strong>:user_id</strong> for the user\'s unique ID and <strong>:term</strong> for the term code.',
		'#default_value' => variable_get('s4_api_db_sql_faculty_courses', ''),
	);
	
	$form['queries']['s4_api_db_sql_user'] = array(
		'#type' => 'textarea',
		'#title' => 'Query to select a user\'s information',
		'#description' => 'Enter the SQL query to collect information about a user. The query should use the following tokens: <strong>:login_id</strong> the ID used to login or authenticate.',
		'#default_value' => variable_get('s4_api_db_sql_user', ''),
	);
	
	return system_settings_form($form);
}

function s4_api_db_admin_form_validate($form, $form_state) {
	try {
	    $db_connect = new PDO($form_state['values']['s4_api_db_dsn'], 
	    					  $form_state['values']['s4_api_db_username'], 
	    					  $form_state['values']['s4_api_db_password']);
		drupal_set_message('Database connection successful.');
	} catch (PDOException $e) {
	    form_set_error('s4_api_db_dsn', 
	    				t('Could not connect. Received message "!message"',
	    					array('!message' => $e->getMessage())));
	}
}

function s4_api_db_s4_get_term($start_date, $end_date) {
	$query = variable_get('s4_api_db_sql_term', FALSE);
	return _s4_api_db_run_query($query, array('start_date' => $start_date,
											  'end_date'   => $end_date));
}

function s4_api_db_s4_get_courses($term) {
	$query = variable_get('s4_api_db_sql_courses', FALSE);
	$courses = _s4_api_db_run_query($query, array('term' => $term));
	return _s4_api_db_add_users_to_courses($term, $courses);
}

function s4_api_db_s4_get_user_enrollment($user_id, $term) {
	$query = variable_get('s4_api_db_sql_user_enrollment', FALSE);
	return _s4_api_db_run_query($query, array('term' => $term,
											  'user_id' => $user_id));
}

function s4_api_db_s4_get_faculty_courses($user_id, $term) {
	$query = variable_get('s4_api_db_sql_faculty_courses', FALSE);
	return _s4_api_db_run_query($query, array('term' => $term,
											  'user_id' => $user_id));
}

function s4_api_db_s4_get_user($login_id) {
	$query = variable_get('s4_api_db_sql_user', FALSE);
	$results =  _s4_api_db_run_query($query, array('login_id' => $login_id));
	if($user_type[0]) {
		$results[0]['restrictions'] = explode(',', $results[0]['restrictions']);
		return $results[0];
	}
	return array();
}

function _s4_api_db_add_users_to_courses($term, $courses) {
	$faculty_query = variable_get('s4_api_db_sql_course_faculty', FALSE);
	$student_query = variable_get('s4_api_db_sql_course_enrollment', FALSE);
	foreach($courses as $key => $course) {
		$courses[$key]['faculty'] = _s4_api_db_run_query($faculty_query, array(
									'term' => $term,
									'subject' => $course['subject'],
									'catalog_number' => $course['catalog_number'],
									'section' => $course['section'],
								));
		foreach($courses[$key]['faculty'] as $key => $user) {
			$courses[$key]['faculty'][$key]['restrictions'] = 
				explode(',', $user['restrictions']);
		}
		
		$courses[$key]['students'] = _s4_api_db_run_query($student_query, array(
									'term' => $term,
									'subject' => $course['subject'],
									'catalog_number' => $course['catalog_number'],
									'section' => $course['section'],
								));
		foreach($courses[$key]['students'] as $key => $user) {
			$courses[$key]['students'][$key]['restrictions'] = 
				explode(',', $user['restrictions']);
		}
	}
	return $courses;
}

function _s4_api_db_run_query($query, $tokens) {
	if(!$query || trim($query) == '') {
		return false;
	}
	try {
	    $sis_db = new PDO(variable_get('s4_api_db_dsn', ''), 
	    					  variable_get('s4_api_db_username', ''), 
	    					  variable_get('s4_api_db_password', ''));
	} catch (PDOException $e) {
	    return false;
	}
	$statement = $sis_db->prepare($query);
	foreach($tokens as $key => $value) {
		$statement->bindValue(':'. $key, $value);
	}
	$statement->execute();
	return $statement->fetchAll(PDO::FETCH_ASSOC);
}