<?php

function s4_reporting_schema() {
  $schema = array();
  
  $schema['s4_reporting'] = array(
    'description' => 'Reporting data',
    'fields' => array(
      'report_key' => array('type' => 'text', 'size' => 'medium', 'not null' => TRUE),
      'date' => array('type' => 'int', 'not null' => TRUE),
      'data' =>    array('type' => 'text', 'size' => 'big', 'not null' => TRUE),
    ),  
  );
  
  return $schema;
}