<?php
/**
 * @file
 * Code for the S4 Editor feature.
 */

include_once('s4_editor.features.inc');

function s4_editor_s4_site_configuration() {
	return array(
		'tinymce-editor' => array(
			'group' => t('Editor'),
			'title' => t('Text editor settings'),
			'href' => 'admin/config/content/wysiwyg/profile/filtered_html/edit',
			'description' => t('Edit what buttons (like bold, italic, underline, etc.) and settings are available in the text editor.'),
		),
	);
}