<?php
/**
 * @file
 * Code for the S4 Map feature.
 */

include_once('s4_map.features.inc');

function s4_map_views_query_alter(&$view, &$query) {
  if ($view->name == 'site_map'){
    $query->where[0]['conditions'][] = array('field' => 'location.latitude',
    									    'value' => floatval($_GET['lat_min']),
    									    'operator' => '>=');
    $query->where[0]['conditions'][] = array('field' => 'location.latitude',
    									    'value' => floatval($_GET['lat_max']),
    									    'operator' => '<=');
    $query->where[0]['conditions'][] = array('field' => 'location.longitude',
    									    'value' => floatval($_GET['lon_min']),
    									    'operator' => '>=');									    
    $query->where[0]['conditions'][] = array('field' => 'location.longitude',
    									    'value' => floatval($_GET['lon_max']),
    									    'operator' => '<=');
  }
}

/**
* Implements hook_s4_site_configuration
*/
function s4_map_s4_site_configuration() {
	return array(
		's4_map' => array(
			'group' => t('Appearance'),
			'title' => t('Map settings'),
			'description' => t('Set the default center and zoom level of your site map.'),
			'href' => 'admin/config/services/gmap',
		),
	);
}

function s4_map_block_info() {
	$blocks['s4_map_site_map'] = array('info' => 'General site map');
	$blocks['s4_map_site_list_map'] = array('info' => 'Site list map');

	return $blocks;
}

function s4_map_block_view($delta) {
	$default = variable_get('gmap_default', array());
	$lat_lon = explode(',', $default['latlong']);
	drupal_add_js(array('s4_map' => array('lat' => $lat_lon[0], 'lon' => $lat_lon[1], 'zoom' => intval($default['zoom']))), 'setting');
	drupal_add_js('https://maps.google.com/maps/api/js?libraries=geometry&sensor=false');
	drupal_add_js(drupal_get_path('module', 's4_map') . '/js/s4_map.js');
	drupal_add_js(array('s4_map_path' => drupal_get_path('module', 's4_map')), 'setting');
	if($program = variable_get('s4_pages_program_homepage', FALSE)) {
  	drupal_add_js(array('s4_map_program' => $program), 'setting');
	}
	drupal_add_css(drupal_get_path('module', 's4_map') . '/css/s4_map.css');
	
	switch($delta) {
		case 's4_map_site_map':
			return array('subject' => null,
						 'content' => '<div id="map-loading-indicator">Loading</div><div class="map autofill" id="site-map"></div>',
						 );
			break;
		case 's4_map_site_list_map':
			return array('subject' => null,
						 'content' => '<div class="map" id="site-list-map"></div>',
						 );
			break;
	}
}