<?php
/**
 * @file
 */
include_once('s4_users.features.inc');

/**
*  Implementation of hook_user_view
*/
function s4_users_user_view($account, $view_mode, $langcode) {
  $account->content['#pre_render'][] = '_s4_users_user_view_pre_render';
  $first_name = field_get_items('user', $account, 'field_first_name');
  $last_name = field_get_items('user', $account, 'field_last_name');
  drupal_set_title(check_plain($first_name[0]['value'] . ' ' . $last_name[0]['value']));
  return $account;
}

/**
*  Prerender callback to remove the history summary from a user profile page
*/
function _s4_users_user_view_pre_render($user) {
  unset($user['summary']);
  return $user;
}

/**
 * Feeds mapper for CAS module
 */
function s4_users_feeds_processor_targets_alter(&$targets, $entity_type, $bundle_name) {
  if ($entity_type == 'user' && module_exists('cas')) {
    $targets['cas_name'] = array(
      'name' => t('CAS User name'),
      'description' => t('A custom field to import user names into CAS.'),
    );
  }
}