<?php

function s4_help_block_info() {
	$blocks['s4_contextual_help'] = array('info' => 'Contextual help');
	return $blocks;
}

function s4_help_block_view($delta) {
	switch($delta) {
		case 's4_contextual_help':
			drupal_add_css('sites/all/libraries/guiders/guiders-1.1.1.css');
			drupal_add_js('sites/all/libraries/guiders/guiders-1.1.1.js');
			drupal_add_js(drupal_get_path('module', 's4_help') .'/js/s4_help.js');
			$help = module_invoke_all('s4_help', $_GET['q']);
			if(count($help)) {
				drupal_add_js(array('s4_help' => $help), 'setting');
				return array('content' => '<a href="#" id="contextual-help">Help</a>');
			}
			break;
	}
}

