<?php

/**
 * Implements hook_feeds_plugins().
 */
function s4_feeds_feeds_plugins() {
  $path = drupal_get_path('module', 's4_feeds') .'/plugins';
  $info['S4CourseEnrollmentProcessor'] = array(
    'name' => 'Course enrollment processor',
    'description' => 'Add and update course enrollment records.',
    'help' => 'Create and update enrollment records from parsed content.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'S4CourseEnrollmentProcessor',
      'file' => 'S4CourseEnrollmentProcessor.inc',
      'path' => $path,
    ),
  );
  $info['S4CourseFaculyProcessor'] = array(
    'name' => 'Course faculty processor',
    'description' => 'Add and update course faculty records.',
    'help' => 'Create and update faculty records from parsed content.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'S4CourseFaculyProcessor',
      'file' => 'S4CourseFaculyProcessor.inc',
      'path' => $path,
    ),
  );
  
  return $info;
}

/**
* Implements hook_s4_site_configuration
*/
function s4_feeds_s4_site_configuration() {
	return array(
		's4_feeds_importers' => array(
			'group' => t('SIS integration'),
			'title' => t('Setup Feed Importers'),
			'description' => t('Build and maintain feed importers.'),
			'href' => 'admin/structure/feeds',
		),
		's4_feeds_import' => array(
			'group' => t('SIS integration'),
			'title' => t('Run and monitor feed importers'),
			'description' => t('Start off feed importers and check on the status of importers.'),
			'href' => 'import',
		),
	);
}