<?php

include_once('s4_opportunity.features.inc');

/**
 * @file
 * Module for the s4_opportunity Entity - a starting point to create your own Entity
 * and associated administration interface
 */


/**
 * Implement hook_entity_info().
 *
 * We define two entities here - the actual entity that will hold our domain
 * specific information and an entity that holds information about the different
 * types of entities. See here: http://drupal.org/node/977380 for a discussion on this
 * choice.
 */
function s4_opportunity_entity_info() {
  $return['s4_opportunity'] = array(
    'label' => t('Opportunity'),
    // The entity class and controller class extend the classes provided by the
    // Entity API
    'entity class' => 's4_opportunity',
    'controller class' => 's4OpportunityController',
    'base table' => 's4_opportunity',
    'fieldable' => TRUE,
    'entity keys' => array(
        'id' => 's4_opportunity_id',
        'bundle' => 'type',
    ),
    // Bundles are defined by the s4_opportunity types below
    'bundles' => array(),
    // Bundle keys tell the FieldAPI how to extract information from the bundle objects
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
    'creation callback' => 's4_opportunity_create',
    'access callback' => 's4_opportunity_access',
    'module' => 's4_opportunity',
    // The information below is used by the s4OpportunityUIController (which extends the EntityDefaultUIController)
    'admin ui' => array(
      'path' => 'admin/content/opportunities',
      'file' => 's4_opportunity.admin.inc',
      'controller class' => 's4OpportunityUIController',
      'menu wildcard' => '%s4_opportunity',
    ),
  );
  // The entity that holds information about the entity types
  $return['s4_opportunity_type'] = array(
    'label' => t('Opportunity Type'),
    'entity class' => 's4_opportunityType',
    'controller class' => 's4OpportunityTypeController',
    'base table' => 's4_opportunity_type',
    'fieldable' => FALSE,
    'bundle of' => 's4_opportunity',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'access callback' => 's4_opportunity_type_access',
    'module' => 's4_opportunity',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/structure/s4_opportunity_types',
      'file' => 's4_opportunity_type.admin.inc',
      'controller class' => 's4OpportunityTypeUIController',
    ),
  );

  return $return;
}


/**
 * Implements hook_entity_info_alter().
 *
 * We are adding the info about the s4_opportunity types via a hook to avoid a recursion
 * issue as loading the s4_opportunity types requires the entity info as well.
 *
 * @todo This needs to be improved
 */
function s4_opportunity_entity_info_alter(&$entity_info) {
  foreach (s4_opportunity_get_types() as $type => $info) {
    $entity_info['s4_opportunity']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/s4_opportunity_types/manage/%s4_opportunity_type',
        'real path' => 'admin/structure/s4_opportunity_types/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => array('administer s4_opportunity types'),
      ),
    );
  }
}


/**
 * Implements hook_permission().
 */
function s4_opportunity_permission() {
  // We set up permisssions to manage entity types, manage all entities and the
  // permissions for each individual entity
  $permissions = array(
    'administer s4_opportunity types' => array(
      'title' => t('Administer s4_opportunity types'),
      'description' => t('Create and delete fields for s4_opportunity types, and set their permissions.'),
    ),
    'administer opportunities' => array(
      'title' => t('Administer opportunities'),
      'description' => t('Edit and delete all opportunities'),
    ),
    'access inactive opportunities' => array(
      'title' => t('Access inactive opportunities'),
      'description' => t('View opportunities that are inactive'),
    ),
    'access active opportunities' => array(
      'title' => t('Access active opportunities'),
      'description' => t('View opportunities that are active'),
    ),
  );

  //Generate permissions per s4_opportunity
  foreach (s4_opportunity_get_types() as $type) {
    $type_name = check_plain($type->type);
    $permissions += array(
      "edit any $type_name s4_opportunity" => array(
        'title' => t('%type_name: Edit any s4_opportunity', array('%type_name' => $type->label)),
      ),
      "view any $type_name s4_opportunity" => array(
        'title' => t('%type_name: View any s4_opportunity', array('%type_name' => $type->label)),
      ),
    );
  }
  return $permissions;
}


/**
 * Determines whether the given user has access to a s4_opportunity.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $s4_opportunity
 *   Optionally a s4_opportunity or a s4_opportunity type to check access for. If nothing is
 *   given, access for all opportunities is determined.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @return boolean
 *   Whether access is allowed or not.
 */
function s4_opportunity_access($op, $s4_opportunity = NULL, $account = NULL) {
  if (user_access('administer opportunities', $account)) {
    return TRUE;
  }
  if ($op == 'view') {
    if ($s4_opportunity->status && user_access('access active opportunities')) {
      return true;
    }
    if (!$s4_opportunity->status && user_access('access inactive opportunities')) {
      return false;
    }
    return false;
  }
  if (isset($s4_opportunity) && $type_name = $s4_opportunity->type) {
    $op = ($op == 'view') ? 'view' : 'edit';
    if (user_access("$op any $type_name s4_opportunity", $account)) {
      return TRUE;
    }
  }
  return FALSE;
}


/**
 * Access callback for the entity API.
 */
function s4_opportunity_type_access($op, $type = NULL, $account = NULL) {
  return user_access('administer s4_opportunity types', $account);
}


/**
 * Gets an array of all s4_opportunity types, keyed by the type name.
 *
 * @param $type_name
 *   If set, the type with the given name is returned.
 * @return s4_opportunityType[]
 *   Depending whether $type isset, an array of s4_opportunity types or a single one.
 */
function s4_opportunity_get_types($type_name = NULL) {
  // entity_load will get the Entity controller for our s4_opportunity entity and call the load
  // function of that object - we are loading entities by name here.
  $types = entity_load_multiple_by_name('s4_opportunity_type', isset($type_name) ? array($type_name) : FALSE);
  return isset($type_name) ? reset($types) : $types;
}


/**
 * Menu argument loader; Load a s4_opportunity type by string.
 *
 * @param $type
 *   The machine-readable name of a s4_opportunity type to load.
 * @return
 *   A s4_opportunity type array or FALSE if $type does not exist.
 */
function s4_opportunity_type_load($type) {
  return s4_opportunity_get_types($type);
}


/**
 * Fetch a s4_opportunity object. Make sure that the wildcard you choose
 * in the s4_opportunity entity definition fits the function name here.
 *
 * @param $s4_opportunity_id
 *   Integer specifying the s4_opportunity id.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   A fully-loaded $s4_opportunity object or FALSE if it cannot be loaded.
 *
 * @see s4_opportunity_load_multiple()
 */
function s4_opportunity_load($s4_opportunity_id, $reset = FALSE) {
  $opportunities = s4_opportunity_load_multiple(array($s4_opportunity_id), array(), $reset);
  return reset($opportunities);
}


/**
 * Load multiple opportunities based on certain conditions.
 *
 * @param $s4_opportunity_ids
 *   An array of s4_opportunity IDs.
 * @param $conditions
 *   An array of conditions to match against the {s4_opportunity} table.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   An array of s4_opportunity objects, indexed by s4_opportunity_id.
 *
 * @see entity_load()
 * @see s4_opportunity_load()
 */
function s4_opportunity_load_multiple($s4_opportunity_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('s4_opportunity', $s4_opportunity_ids, $conditions, $reset);
}


/**
 * Deletes a s4_opportunity.
 */
function s4_opportunity_delete(s4_opportunity $s4_opportunity) {
  $s4_opportunity->delete();
}


/**
 * Delete multiple opportunities.
 *
 * @param $s4_opportunity_ids
 *   An array of s4_opportunity IDs.
 */
function s4_opportunity_delete_multiple(array $s4_opportunity_ids) {
  entity_get_controller('s4_opportunity')->delete($s4_opportunity_ids);
}


/**
 * Create a s4_opportunity object.
 */
function s4_opportunity_create($values = array()) {
  return entity_get_controller('s4_opportunity')->create($values);
}


/**
 * Saves a s4_opportunity to the database.
 *
 * @param $s4_opportunity
 *   The s4_opportunity object.
 */
function s4_opportunity_save(s4_opportunity $s4_opportunity) {
  return $s4_opportunity->save();
}


/**
 * Saves a s4_opportunity type to the db.
 */
function s4_opportunity_type_save(s4_opportunityType $type) {
  $type->save();
}


/**
 * Deletes a s4_opportunity type from the db.
 */
function s4_opportunity_type_delete(s4_opportunityType $type) {
  $type->delete();
}


/**
 * URI callback for opportunities
 */
function s4_opportunity_uri(s4_opportunity $s4_opportunity){
  return array(
    'path' => 's4_opportunity/' . $s4_opportunity->s4_opportunity_id,
  );
}


/**
 * Menu title callback for showing individual entities
 */
function s4_opportunity_page_title(s4_opportunity $s4_opportunity){
  return $s4_opportunity->name;
}


/**
 * Sets up content to show an individual s4_opportunity
 * @todo - get rid of drupal_set_title();
 */
function s4_opportunity_page_view($s4_opportunity, $view_mode = 'full') {
  $controller = entity_get_controller('s4_opportunity');
  $content = $controller->view(array($s4_opportunity->s4_opportunity_id => $s4_opportunity));
  drupal_set_title($s4_opportunity->name);
  return $content;
}

/**
 * Implement hook_theme().
 */
function s4_opportunity_theme() {
  return array(
    's4_opportunity_add_list' => array(
      'variables' => array('content' => array()),
      'file' => 's4_opportunity.admin.inc',
    ),
    's4_opportunity' => array(
      'render element' => 'elements',
      'template' => 's4_opportunity',
    ),
  );
}

function s4_opportunity_s4_site_configuration() {
  return array(
    'opportunity_types' => array(
      'group' => t('Opportunities'),
      'title' => t('Opportunity types'),
      'description' => t('Define types of opportunities like internships or special projects.'),
      'href' => 'admin/structure/s4_opportunity_types',
    ),
  );
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function s4_opportunity_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link 'admin/structure/opportunities/add' on 'admin/structure/opportunities'.
  if ($root_path == 'admin/content/opportunities') {
    $item = menu_get_item('opportunities/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Implements hook_block_info().
 */
function s4_opportunity_block_info() {
  return array(
    'new_opportunity' => array('info' => t('Create opportunity form')),
    );
}

/**
 * Implements hook_
 */
function s4_opportunity_block_view($delta) {
  module_load_include('inc', 's4_opportunity', 's4_opportunity.block');
  switch($delta) {
    case 'new_opportunity':
      return array('subject' => t('Create new opportunity'),
        'content' => drupal_get_form('s4_opportunity_create_form'));
  }
}

/**
 * Add default fields to new opportunity types
 */
function s4_opportunity_add_default_fields($type) {
  $field = field_info_field('field_opportunity_sites');
  $instance = field_info_instance('s4_opportunity', 'field_opportunity_sites', $type);
  if (empty($field)) {
    $field = array(
      'active' => '1',
      'cardinality' => '-1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_opportunity_sites',
      'foreign keys' => array(
        'node' => array(
          'columns' => array(
            'target_id' => 'nid',
          ),
          'table' => 'node',
        ),
      ),
      'indexes' => array(
        'target_id' => array(
          0 => 'target_id',
        ),
      ),
      'module' => 'entityreference',
      'settings' => array(
        'handler' => 'base',
        'handler_settings' => array(
          'behaviors' => array(
            'views-select-list' => array(
              'status' => 0,
            ),
          ),
          'sort' => array(
            'type' => 'none',
          ),
          'target_bundles' => array(
            'site' => 'site',
          ),
        ),
        'target_type' => 'node',
      ),
      'translatable' => '0',
      'type' => 'entityreference',
    );
    $field = field_create_field($field);
  }
  if (empty($instance)) {
    $instance = array(
      'bundle' => $type,
      'default_value' => NULL,
      'default_value_function' => 'entityreference_prepopulate_field_default_value',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'entityreference',
          'settings' => array(
            'link' => FALSE,
          ),
          'type' => 'entityreference_label',
          'weight' => 14,
        ),
      ),
      'display_label' => '',
      'entity_type' => 's4_opportunity',
      'field_name' => 'field_opportunity_sites',
      'label' => 'Sites',
      'required' => 0,
      'settings' => array(
        'behaviors' => array(
          'prepopulate' => array(
            'action' => 'hide',
            'action_on_edit' => 1,
            'fallback' => 'hide',
            'og_context' => 0,
            'skip_perm' => '0',
            'status' => 1,
          ),
        ),
        'custom_add_another' => '',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'entityreference',
        'settings' => array(
          'match_operator' => 'CONTAINS',
          'path' => '',
          'size' => '60',
        ),
        'type' => 'entityreference_autocomplete',
        'weight' => '7',
      ),
    );
    $instance = field_create_instance($instance);
  }

  $field = field_info_field('field_opportunity_site_staff');
  $instance = field_info_instance('s4_opportunity', 'field_opportunity_site_staff', $type);
  if (empty($field)) {
    $field = array(
		  'active' => '1',
      'cardinality' => '-1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_opportunity_site_staff',
      'foreign keys' => array(
        'node' => array(
          'columns' => array(
            'target_id' => 'nid',
          ),
          'table' => 'node',
        ),
      ),
      'indexes' => array(
        'target_id' => array(
          0 => 'target_id',
        ),
      ),
      'module' => 'entityreference',
      'settings' => array(
        'handler' => 'base',
        'handler_settings' => array(
          'behaviors' => array(
            'views-select-list' => array(
              'status' => 0,
            ),
          ),
          'sort' => array(
            'type' => 'none',
          ),
          'target_bundles' => array(
            'coordinator' => 'coordinator',
          ),
        ),
        'target_type' => 'node',
      ),
      'translatable' => '0',
      'type' => 'entityreference',
		);
    $field = field_create_field($field);
  }
  if (empty($instance)) {
    $instance = array(
      'bundle' => $type,
      'default_value' => NULL,
      'default_value_function' => 'entityreference_prepopulate_field_default_value',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'entityreference',
          'settings' => array(
            'link' => FALSE,
          ),
          'type' => 'entityreference_label',
          'weight' => 15,
        ),
      ),
      'display_label' => '',
      'entity_type' => 's4_opportunity',
      'field_name' => 'field_opportunity_site_staff',
      'label' => 'Site staff',
      'required' => 0,
      'settings' => array(
        'behaviors' => array(
          'prepopulate' => array(
            'action' => 'hide',
            'action_on_edit' => 1,
            'fallback' => 'hide',
            'og_context' => 0,
            'skip_perm' => '0',
            'status' => 1,
          ),
        ),
        'custom_add_another' => '',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'entityreference',
        'settings' => array(
          'match_operator' => 'CONTAINS',
          'path' => '',
          'size' => '60',
        ),
        'type' => 'entityreference_autocomplete',
        'weight' => '8',
      ),
    );
    $instance = field_create_instance($instance);
  }


  $field = field_info_field('field_site_restrict');
  $instance = field_info_instance('s4_opportunity', 'field_site_restrict', $type);
  if (empty($field)) {
    $field = array(
		  'entity_types' => array(),
		  'foreign keys' => array(
		    'tid' => array(
		      'columns' => array(
		        'tid' => 'tid',
		      ),
		      'table' => 'taxonomy_term_data',
		    ),
		  ),
		  'global_block_settings' => '2',
		  'indexes' => array(
		    'tid' => array(
		      'tid',
		    ),
		  ),
		  'settings' => array(
		    'allowed_values' => array(
		      array(
		        'vocabulary' => 'site_restrictions',
		        'parent' => '0',
		      ),
		    ),
		  ),
		  'translatable' => '1',
		  'storage' => array(
		    'type' => 'field_sql_storage',
		    'settings' => array(),
		    'module' => 'field_sql_storage',
		    'active' => '1',
		    'details' => array(
		      'sql' => array(
		        'FIELD_LOAD_CURRENT' => array(
		          'field_data_field_site_restrict' => array(
		            'tid' => 'field_site_restrict_tid',
		          ),
		        ),
		        'FIELD_LOAD_REVISION' => array(
		          'field_revision_field_site_restrict' => array(
		            'tid' => 'field_site_restrict_tid',
		          ),
		        ),
		      ),
		    ),
		  ),
		  'field_name' => 'field_site_restrict',
		  'type' => 'taxonomy_term_reference',
		  'module' => 'taxonomy',
		  'active' => '1',
		  'locked' => '0',
		  'cardinality' => '-1',
		  'deleted' => '0',
		  'columns' => array(
		    'tid' => array(
		      'type' => 'int',
		      'unsigned' => TRUE,
		      'not null' => FALSE,
		    ),
		  ),
		  'bundles' => array(
		    'field_collection_item' => array(
		      'field_site_evaluation_group',
		      'field_site_signup_group',
		    ),
		    'node' => array(
		      'coordinator',
		      'site',
		      'downloadable_form',
		      'signup',
		      'course',
		      'webform',
		    ),
		    'user' => array(
		      'user',
		    ),
		  ),
		);
    $field = field_create_field($field);
  }
  if (empty($instance)) {
    $instance = array(
      'bundle' => $type,
      'entity_type' => 's4_opportunity',
		  'default_value' => NULL,
		  'description' => 'Select which programs can access this site.',
		  'display' => array(
		    'default' => array(
		      'label' => 'above',
		      'type' => 'taxonomy_term_reference_plain',
		      'weight' => '11',
		      'settings' => array(),
		      'module' => 'taxonomy',
		    ),
		    'full' => array(
		      'label' => 'above',
		      'settings' => array(),
		      'type' => 'hidden',
		      'weight' => '5',
		    ),
		    'notifications' => array(
		      'label' => 'above',
		      'settings' => array(),
		      'type' => 'hidden',
		      'weight' => 0,
		    ),
		    'teaser' => array(
		      'label' => 'above',
		      'settings' => array(),
		      'type' => 'hidden',
		      'weight' => 0,
		    ),
		    'search_index' => array(
		      'label' => 'above',
		      'type' => 'hidden',
		      'weight' => '2',
		      'settings' => array(),
		    ),
		  ),
		  'display_label' => '',
		  'label' => 'Program(s)',
		  'required' => 1,
		  's4_sites_field_access' => 0,
		  'settings' => array(
		    'user_register_form' => FALSE,
		    'custom_add_another' => '',
		  ),
		  'widget' => array(
		    'weight' => '4',
		    'type' => 'options_buttons',
		    'module' => 'options',
		    'active' => 1,
		    'settings' => array(),
		  ),
		  'field_name' => 'field_site_restrict',
		  'deleted' => '0',
		);
    $instance = field_create_instance($instance);
  }

  $field = field_info_field('field_active_date');
  $instance = field_info_instance('s4_opportunity', 'field_active_date', $type);
  if (empty($field)) {
    $field = array(
		  'translatable' => '0',
		  'entity_types' => array(),
		  'settings' => array(
		    'granularity' => array(
		      'month' => 'month',
		      'day' => 'day',
		      'year' => 'year',
		      'hour' => 0,
		      'minute' => 0,
		      'second' => 0,
		    ),
		    'tz_handling' => 'none',
		    'timezone_db' => '',
		    'cache_enabled' => 0,
		    'cache_count' => '4',
		    'todate' => 'required',
		  ),
		  'storage' => array(
		    'type' => 'field_sql_storage',
		    'settings' => array(),
		    'module' => 'field_sql_storage',
		    'active' => '1',
		    'details' => array(
		      'sql' => array(
		        'FIELD_LOAD_CURRENT' => array(
		          'field_data_field_active_date' => array(
		            'value' => 'field_active_date_value',
		            'value2' => 'field_active_date_value2',
		          ),
		        ),
		        'FIELD_LOAD_REVISION' => array(
		          'field_revision_field_active_date' => array(
		            'value' => 'field_active_date_value',
		            'value2' => 'field_active_date_value2',
		          ),
		        ),
		      ),
		    ),
		  ),
		  'foreign keys' => array(),
		  'indexes' => array(),
		  'field_name' => 'field_active_date',
		  'type' => 'datetime',
		  'module' => 'date',
		  'active' => '1',
		  'locked' => '0',
		  'cardinality' => '1',
		  'deleted' => '0',
		  'columns' => array(
		    'value' => array(
		      'type' => 'datetime',
		      'mysql_type' => 'datetime',
		      'pgsql_type' => 'timestamp without time zone',
		      'sqlite_type' => 'varchar',
		      'sqlsrv_type' => 'smalldatetime',
		      'not null' => FALSE,
		      'sortable' => TRUE,
		      'views' => TRUE,
		    ),
		    'value2' => array(
		      'type' => 'datetime',
		      'mysql_type' => 'datetime',
		      'pgsql_type' => 'timestamp without time zone',
		      'sqlite_type' => 'varchar',
		      'sqlsrv_type' => 'smalldatetime',
		      'not null' => FALSE,
		      'sortable' => TRUE,
		      'views' => FALSE,
		    ),
		  ),
		  'bundles' => array(
		    's4_opportunity' => array(
		      $type,
		    ),
		  ),
		);
    $field = field_create_field($field);
  }

  if (empty($instance)) {
    $instance = array(
		  'label' => 'Active date',
		  'widget' => array(
		    'weight' => '6',
		    'type' => 'date_popup',
		    'module' => 'date',
		    'active' => 1,
		    'settings' => array(
		      'input_format' => 'm/d/Y - H:i:s',
		      'input_format_custom' => '',
		      'year_range' => '-3:+3',
		      'increment' => '15',
		      'label_position' => 'above',
		      'text_parts' => array(),
		      'display_all_day' => 0,
		    ),
		  ),
		  'settings' => array(
		    'default_value' => 'now',
		    'default_value_code' => '',
		    'default_value2' => 'strtotime',
        'default_value_code2' => '+1 year',
		    'custom_add_another' => '',
		    'user_register_form' => FALSE,
		  ),
		  'display' => array(
		    'default' => array(
		      'label' => 'above',
		      'type' => 'date_default',
		      'settings' => array(
		        'format_type' => 'long',
		        'multiple_number' => '',
		        'multiple_from' => '',
		        'multiple_to' => '',
		        'fromto' => 'both',
		      ),
		      'module' => 'date',
		      'weight' => 13,
		    ),
		  ),
		  'required' => 0,
		  'description' => 'Select the time when this opportunity is available.',
		  'display_label' => '',
		  'field_name' => 'field_active_date',
		  'entity_type' => 's4_opportunity',
		  'bundle' => $type,
		  'deleted' => '0',
		);
    $instance = field_create_instance($instance);
  }

  $field = field_info_field('field_maximum_placements');
  $instance = field_info_instance('s4_opportunity', 'field_maximum_placements', $type);
  if (empty($field)) {
    $field = array(
		  'translatable' => '0',
		  'entity_types' => array(),
		  'settings' => array(),
		  'storage' => array(
		    'type' => 'field_sql_storage',
		    'settings' => array(),
		    'module' => 'field_sql_storage',
		    'active' => '1',
		    'details' => array(
		      'sql' => array(
		        'FIELD_LOAD_CURRENT' => array(
		          'field_data_field_maximum_placements' => array(
		            'value' => 'field_maximum_placements_value',
		          ),
		        ),
		        'FIELD_LOAD_REVISION' => array(
		          'field_revision_field_maximum_placements' => array(
		            'value' => 'field_maximum_placements_value',
		          ),
		        ),
		      ),
		    ),
		  ),
		  'foreign keys' => array(),
		  'indexes' => array(),
		  'field_name' => 'field_maximum_placements',
		  'type' => 'number_integer',
		  'module' => 'number',
		  'active' => '1',
		  'locked' => '0',
		  'cardinality' => '1',
		  'deleted' => '0',
		  'columns' => array(
		    'value' => array(
		      'type' => 'int',
		      'not null' => FALSE,
		    ),
		  ),
		  'bundles' => array(
		    's4_opportunity' => array(
		      $type,
		    ),
		  ),
		);
    $field = field_create_field($field);
  }
  if (empty($instance)) {
    $instance = array(
		  'label' => 'Maximum placements',
		  'widget' => array(
		    'weight' => '5',
		    'type' => 'number',
		    'module' => 'number',
		    'active' => 0,
		    'settings' => array(),
		  ),
		  'settings' => array(
		    'min' => '',
		    'max' => '',
		    'prefix' => '',
		    'suffix' => '',
		    'custom_add_another' => '',
		    'user_register_form' => FALSE,
		  ),
		  'display' => array(
		    'default' => array(
		      'label' => 'above',
		      'type' => 'number_integer',
		      'settings' => array(
		        'thousand_separator' => ' ',
		        'decimal_separator' => '.',
		        'scale' => 0,
		        'prefix_suffix' => TRUE,
		      ),
		      'module' => 'number',
		      'weight' => 12,
		    ),
		  ),
		  'required' => 0,
		  'description' => 'Enter the maximum number of placements that can be made at any given time.',
		  'display_label' => '',
		  'default_value' => NULL,
		  'field_name' => 'field_maximum_placements',
		  'entity_type' => 's4_opportunity',
		  'bundle' => $type,
		  'deleted' => '0',
		);
    $instance = field_create_instance($instance);
  }
  $field = field_info_field('field_opportunity_category');
  $instance = field_info_instance('s4_opportunity', 'field_opportunity_category', $type);
  if (empty($field)) {
    $field = array(
      'translatable' => '0',
      'entity_types' => array(),
      'settings' => array(
        'allowed_values' => array(
          array(
            'vocabulary' => 'opportunity_category',
            'parent' => '0',
          ),
        ),
      ),
      'storage' => array(
        'type' => 'field_sql_storage',
        'settings' => array(),
        'module' => 'field_sql_storage',
        'active' => '1',
        'details' => array(
          'sql' => array(
            'FIELD_LOAD_CURRENT' => array(
              'field_data_field_opportunity_category' => array(
                'tid' => 'field_opportunity_category_tid',
              ),
            ),
            'FIELD_LOAD_REVISION' => array(
              'field_revision_field_opportunity_category' => array(
                'tid' => 'field_opportunity_category_tid',
              ),
            ),
          ),
        ),
      ),
      'foreign keys' => array(
        'tid' => array(
          'table' => 'taxonomy_term_data',
          'columns' => array(
            'tid' => 'tid',
          ),
        ),
      ),
      'indexes' => array(
        'tid' => array(
          'tid',
        ),
      ),
      'field_name' => 'field_opportunity_category',
      'type' => 'taxonomy_term_reference',
      'module' => 'taxonomy',
      'active' => '1',
      'locked' => '0',
      'cardinality' => '-1',
      'deleted' => '0',
      'columns' => array(
        'tid' => array(
          'type' => 'int',
          'unsigned' => TRUE,
          'not null' => FALSE,
        ),
      ),
      'bundles' => array(
        's4_opportunity' => array(
          $type,
        ),
      ),
    );
    $field = field_create_field($field);
  }
  if (empty($instance)) {
    $instance = array(
      'bundle' => $type,
      'label' => 'Category',
      'widget' => array(
        'weight' => '9',
        'type' => 'options_select',
        'module' => 'options',
        'active' => 1,
        'settings' => array(),
      ),
      'settings' => array(
        'custom_add_another' => '',
        'user_register_form' => FALSE,
      ),
      'display' => array(
        'default' => array(
          'label' => 'above',
          'type' => 'taxonomy_term_reference_link',
          'settings' => array(),
          'module' => 'taxonomy',
          'weight' => 16,
        ),
      ),
      'required' => 0,
      'description' => '',
      'display_label' => '',
      'default_value' => NULL,
      'field_name' => 'field_opportunity_category',
      'entity_type' => 's4_opportunity',
      'deleted' => '0',
    );
    $instance = field_create_instance($instance);
  }
}

function s4_opportunity_form_field_ui_field_edit_form_alter(&$form, $form_state) {
  if ($form['#instance']['entity_type'] != 's4_opportunity') {
    return null;
  }
  
  $form['instance']['s4_opportunity_risk'] = array(
    '#type' => 'checkbox',
    '#title' => t('This is a risk-management field'),
    '#default_value' => ($form['#instance']['s4_opportunity_risk']) ? $form['#instance']['s4_opportunity_risk'] : FALSE,
  );

}

/**
 * The class used for s4_opportunity entities
 */
class s4_opportunity extends Entity {

  public function __construct($values = array()) {
    parent::__construct($values, 's4_opportunity');
  }

  protected function defaultLabel() {
    return $this->name;
  }

  protected function defaultUri() {
    return array('path' => 'opportunity/' . $this->s4_opportunity_id);
  }


}


/**
 * The class used for s4_opportunity type entities
 */
class s4_opportunityType extends Entity {

  public $type;
  public $label;

  public function __construct($values = array()) {
    parent::__construct($values, 's4_opportunity_type');
  }

}


/**
 * The Controller for s4_opportunity entities
 */
class s4OpportunityController extends EntityAPIController {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }


  /**
   * Create a s4_opportunity - we first set up the values that are specific
   * to our s4_opportunity schema but then also go through the EntityAPIController
   * function.
   *
   * @param $type
   *   The machine-readable type of the s4_opportunity.
   *
   * @return
   *   A s4_opportunity object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our s4_opportunity
    $values += array(
      's4_opportunity_id' => '',
      'is_new' => TRUE,
      'title' => '',
      'created' => '',
      'changed' => '',
      'data' => '',
    );

    $s4_opportunity = parent::create($values);
    return $s4_opportunity;
  }

  /**
   * Overriding the buldContent function to add entity specific fields
   */
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
    $content = parent::buildContent($entity, $view_mode, $langcode, $content);
    return $content;
  }

}


/**
 * The Controller for s4_opportunity entities
 */
class s4OpportunityTypeController extends EntityAPIControllerExportable {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }

   /**
   * Create a s4_opportunity type - we first set up the values that are specific
   * to our s4_opportunity type schema but then also go through the EntityAPIController
   * function.
   *
   * @param $type
   *   The machine-readable type of the s4_opportunity.
   *
   * @return
   *   A s4_opportunity type object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our s4_opportunity
    $values += array(
      'id' => '',
      'is_new' => TRUE,
      'data' => '',
    );
    $s4_opportunity_type = parent::create($values);
    return $s4_opportunity_type;
  }

}

function s4_opportunity_views_data_alter(&$data) { 
  $data['s4_opportunity']['table']['base'] = array(
    'field' => 's4_opportunity_id',
    'title' => t('Opportunity'),
    'weight' => -10,
    'access query tag' => 's4_opportunity_access',
    'defaults' => array(
      'field' => 'status',
    ),
  );

  $data['s4_opportunity']['name'] = array(
    'title' => t('Name'),
    'help' => t('Name and optional link to opportunity.'),
    'field' => array(
      'handler' => 's4_opportunity_handler_name',
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );


  $data['s4_opportunity']['s4_opportunity_id'] = array(
    'title' => t('ID'),
    'help' => t('The unique ID of this opportunity.'),
    'field' => array(
      'handler' => 'views_handler_field',
    ),
  );

  $data['s4_opportunity']['status'] = array(
    'field' => array(
      'title' => t('Status'),
      'help' => t('Status of the opportunity.'),
      'handler' => 's4_opportunity_handler_status',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_boolean_operator',
      'title' => t('Status'),
      'label' => t('Status'),
      'type' => 'yes-no',
      'use equal' => TRUE, // Use status = 1 instead of status <> 0 in WHERE statment
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
  );

  $data['s4_opportunity']['type'] = array(
    'field' => array(
      'title' => t('Opportunity type'),
      'help' => t('Type of opportunity.'),
      'handler' => 's4_opportunity_handler_type',
    ),
  );

  $data['s4_opportunity']['edit_s4_opportunity'] = array(
    'field' => array(
      'title' => t('Edit Link'),
      'help' => t('Provide a link to the edit form for the s4_opportunity.'),
      'handler' => 's4_opportunity_handler_edit_link_field',
    ),
  );
  $data['s4_opportunity']['delete_s4_opportunity'] = array(
    'field' => array(
      'title' => t('Delete Link'),
      'help' => t('Provide a link to delete the s4_opportunity.'),
      'handler' => 's4_opportunity_handler_delete_link_field',
    ),
  );
  // This content of this field are decided based on the menu structure that
  // follows s4_opportunitys/s4_opportunity/%s4_opportunity_id/op
  $data['s4_opportunity']['operations'] = array(
    'field' => array(
      'title' => t('Operations links'),
      'help' => t('Display all operations available for this s4_opportunity.'),
      'handler' => 's4_opportunity_handler_s4_opportunity_operations_field',
    ),
  );
}